### ISSUE TITLE
Bot Wide Command Disable

### ISSUE THREAD

**Issue by Flat** [paul-io/momo-2#1]
Would be handy for the owner to be able to disable commands bot wide using commands without editing the template.properties file for new guilds.

**Comment by paul-io** [comment]
Disable commands for all guilds?

**Comment by Flat** [comment]
Correct, say if you don't want any guild to be able to use `imgur` for example.

**Comment by paul-io** [comment]
What doesn't work about editing `template.properties`? I guess, if you want to have some more legroom to enable/disable whenever you want?

**Comment by Flat** [comment]
Editing `template.properties` is fine, but it is not applied retroactive correct? You'd have to go back and edit the individual guild properties to disable the commands - or delete the guild config and restart the bot to re-create them.

**Comment by paul-io** [comment]
f9109a9a409f5c62d184723e0c8d93373d40b356 should be sufficient

**Comment by Flat** [comment]
That was quick, thanks! On an unrelated note - your example on momobot.io for the `wow` command has the example for `leaverole` instead.

**Comment by paul-io** [comment]
Haha yeah... There are a lot of issues with that page. Having it generate from the actual commands rather than hardwriting it is on the horizon
