### ISSUE TITLE
play command issue

### ISSUE THREAD

**Issue by Cloudy6634** [paul-io/momo-2#11]
hello,
seems like there is a problem with $play command on music video, i don't really know why but the music instantly stop and momo diplay the following message
> "Queue finished!
> Your queue is all dried up"
is it just me? maybe something goes wrong with youtube?

here is a screenshot of my cmd.exe :
[https://puu.sh/ziQHU.png](url) (copy/paste on new tab)
Thanks for help in advance.

**Comment by paul-io** [comment]
Please try out the new build here and let me know how it goes: https://github.com/paul-io/momo-2/releases/tag/v2.1.0

**Comment by paul-io** [comment]
Great, no problem!
