### ISSUE TITLE
Prefix

### ISSUE THREAD

**Issue by Terax235** [paul-io/momo-2#3]
However, I can't set the Bots Prefix. I searched in the `Bot.properties`, and I tried `Prefix=!`, but it didn't work.

Also, you shall update the Bot a bit because of the new Channel Categories

**Comment by paul-io** [comment]
Will update dependencies to make it work very soon - also, prefixes are guild-specific. You can look in `resources/guilds/template.properties` to see the default. This gets copied to every new guild, but if you want to change yours through the file, look in `resources/guilds/guild_id/GuildProperties.properties`
