### ISSUE TITLE
Local host, cannot add to more than 1 servers

### ISSUE THREAD

**Issue by Cloudy6634** [paul-io/momo-2#5]
Hello there,
since i've met your creation (momo) and added it in my server i was really enjoying the simple functionality and the manner that she work, i've seen your post and tutorial how to host the bot and now host myself for me and one of my friends (2 servers) but it's seems simply impossible to do so. i'm not a noob, but not good in the coding world (was used to code on linux python and perl) but momo refuses to connect to any other servers, first i've got the URI problem, and next the bot simply redirect me to the dashboard page. is there any limitation? maybe can i have the hint/tutorial to easily share my bot with my friend? of course i will host it (because my friend have a terrible internet connection).
and by the way, is the osu functionality not finish? i cannot use it at all. (update : just added the api key into the Bot.properties and works propely)
thanks in advance for answer :)

**Comment by Cloudy6634** [comment]
PS : Your Dashboard is not accesible aswell, asking permission but not opening the dashboard itself.

**Comment by paul-io** [comment]
So it works well after you added the API key? Also, what do you mean it isn't accessible? Got a screenshot, or errors?

**Comment by Cloudy6634** [comment]
Yes the osu functionnality work properly just by adding the line 
`# Osu Api Key for osu looks up https://osu.ppy.sh/p/api
apikey.osu=insertyourapikeyhere`

"your dashboard" category it's kinda simple. I wanna access to "your dashboard" on momo dashboard and it redirect me to a discord page for momo to look which server i use and had access to some information if you click "Accept" it redirect me to the index page of momo's dashboard, no error message or anything
[https://puu.sh/ytQBR.png](url)
[https://puu.sh/ytQoW.png](url)

and for the sharing momo to my friend servers, it's simply do the same, once i've generate the OAuth2 URL and try to get momo on different server, then it teleport me or my friend into the momo index dashboard page.

**Comment by Flat** [comment]
To add the bot to a new server you want to use this link https://discordapp.com/oauth2/authorize?client_id=383687431930511363&scope=bot&permissions=37088320

For the dashboard you need to go to https://discordapp.com/developers/applications/me#top and then set the "redirect uri" (Not sure what it would be in your langauge) to yzzgaming.ddns.net:8080/callback and then the dashboard should work.

**Comment by Cloudy6634** [comment]
Hello,
Thank you flat for your answer, you were right about the dashboard it's now working propely, i managed to invite my bot to another discord server by simply deleteing the "&redirect_uri=http%3A%2F%2Fyzzgaming.ddns.net%3A8080%2Fcallback" in the link which seems to work now, your link was good but was actually asking for code grant for some reason.
otherwise thank you so much for you help, appreciate it :)
