### ISSUE TITLE
Dashboard

### ISSUE THREAD

**Issue by Cloudy6634** [paul-io/momo-2#6]
hello again,
it's seems like my friend cannot change anything in the bot dashboard, i tried it myself on my own server and the dashboard doesn't work. i can only see a small loading bar on top-right corner of my screen that disappears after few seconds, but doesn't save the change i made.
btw is there a way to put ALL text into a single text channel (for example affect $osu, $ow, etc. and momo responds to a single text channel)

**Comment by paul-io** [comment]
1) Can you post what shows up on the console when someone tries to access the dashboard?

2) There isn't a way to restrict commands to a certain channel. You'll have to edit Momo's permissions in the server and channels

**Comment by Cloudy6634** [comment]
Thanks for the Answer paul
1.[https://puu.sh/ywajl.png](url) Screenshot of command prompt Highlight = access dashboard + trying to modify welcome message.

2. so in short, i have to modify the momox.x.x.jar file?
Thanks for the help

**Comment by Cloudy6634** [comment]
missclick sorry lol

**Comment by Flat** [comment]
That error is saying you don't have a Reddit api key set in the properties file. As for restricting momo to one channel, you can just set it so momo can't read any channel but the one you want using discord permissions

**Comment by Cloudy6634** [comment]
hey @Flat,
i was checking in bot.properties there are no set for $osu, $ow commands. so i guess it's include rewrite?

**Comment by Flat** [comment]
Yes there is no way to currently set commands to specific channels.

**Comment by Cloudy6634** [comment]
@Flat no way or no other way? otherwise if i have to rewrite i would gladly try to work on it. 
As well as expanding $osu command with more information, but i never heard of a .jar file editor? maybe do you got an hint?

**Comment by Flat** [comment]
There is no way. You can restrict momo to one channel via Discord. If you want the ability to restrict a command to one channel it will have to be added to momo. You will need to know how to program in Java to implement this - or hope someone else adds the feature in the future.

**Comment by Cloudy6634** [comment]
@Flat thanks for the answer.
